# Generated by Django 5.2.6 on 2025-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
