# Generated by Django 5.2.6 on 2025-09-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_current_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='target_class',
            field=models.IntegerField(),
        ),
    ]
