# Generated by Django 5.2.6 on 2025-09-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_milestone_target_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='goals',
        ),
    ]
